# Generated by Django 4.2.16 on 2026-03-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_te', models.CharField(blank=True, max_length=100)),
                ('name_hi', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('original_title', models.CharField(max_length=300)),
                ('overview', models.TextField()),
                ('release_year', models.IntegerField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('popularity', models.FloatField(default=0)),
                ('language', models.CharField(max_length=10)),
                ('poster_path', models.CharField(blank=True, max_length=200)),
                ('backdrop_path', models.CharField(blank=True, max_length=200)),
                ('streaming_platforms', models.JSONField(default=dict)),
                ('is_curated_seed', models.BooleanField(default=False)),
                ('is_family_safe', models.BooleanField(default=True)),
                ('content_warning', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
        migrations.CreateModel(
            name='ReportedPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong_mood', 'Wrong mood'), ('wrong_language', 'Wrong language'), ('inappropriate', 'Inappropriate content'), ('already_seen', 'Already seen this'), ('bad_quality', 'Bad film quality'), ('other', 'Other')], max_length=50)),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
